development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: pjfamig@gmail.com
  :password: feisal1985
  :enable_starttls_auto: true
  
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: pjfamig@gmail.com
  :password: feisal1985
  :enable_starttls_auto: true