development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: paul@paulfamiglietti.com
  :password: lIveacROssWIrE
  :enable_starttls_auto: true
  
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: paul@paulfamiglietti.com
  :password: lIveacROssWIrE
  :enable_starttls_auto: true